language: node_js
node_js:
    - 8.11.1
cache:
    directories:
        - $HOME/.cache
install:
    - yarn global add @dhis2/deploy-build
    - yarn install --frozen-lockfile
    - yarn cy:verify
script:
    - yarn build
    - yarn start &> /dev/null &
    - yarn cy:stub:run
    - kill $(jobs -p) || true
deploy:
    - provider: script
      script: deploy-build
      skip_cleanup: true
      on:
          all_branches: true
