language: node_js

node_js:
  - '10'

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'
env:
  - REACT_APP_DHIS2_URL_TEST=https://play.dhis2.org/2.30 REACT_APP_URL_TEST=http://localhost:9000 START_SERVER=true

script:
- yarn run test:all
